import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
} from "../colors";

const level = {
  path: "/community-level/371",
  size: 15,
  colorRegions: [
    ["H", "O", "O", "H", "H", "E", "D", "H", "H", "H", "H", "H", "E", "H", "A"],
    ["H", "O", "O", "H", "M", "H", "D", "D", "D", "H", "E", "H", "H", "H", "H"],
    ["H", "H", "M", "H", "H", "H", "H", "D", "D", "D", "D", "H", "H", "H", "H"],
    ["H", "H", "H", "C", "C", "M", "H", "H", "D", "H", "H", "H", "H", "E", "H"],
    ["G", "H", "H", "C", "C", "H", "H", "H", "D", "H", "B", "B", "B", "H", "H"],
    ["G", "G", "H", "H", "H", "H", "M", "H", "D", "J", "J", "J", "J", "J", "H"],
    ["G", "G", "H", "M", "H", "F", "F", "H", "D", "H", "B", "B", "B", "H", "H"],
    ["G", "G", "H", "H", "H", "F", "F", "H", "D", "H", "H", "H", "H", "H", "H"],
    ["G", "G", "H", "E", "H", "H", "H", "H", "D", "D", "D", "H", "K", "K", "H"],
    ["G", "G", "H", "H", "H", "H", "H", "D", "D", "H", "H", "H", "K", "K", "H"],
    ["G", "H", "H", "H", "H", "H", "H", "D", "D", "D", "D", "H", "H", "H", "H"],
    ["H", "E", "H", "H", "H", "E", "D", "D", "L", "L", "L", "H", "H", "N", "N"],
    ["H", "H", "H", "H", "H", "H", "D", "H", "L", "L", "L", "H", "H", "N", "N"],
    ["H", "H", "I", "I", "H", "D", "D", "H", "L", "L", "L", "H", "E", "H", "H"],
    ["H", "H", "I", "I", "H", "D", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
  },
  solutionsCount: 1,
  createdBy: "Dan Relaxxe",
  creatorLink: "",
};

export default level;
