import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/409",
  size: 18,
  colorRegions: [
    ["Q", "C", "C", "R", "R", "N", "N", "N", "N", "N", "N", "N", "C", "C", "R", "C", "C", "C"],
    ["C", "C", "R", "R", "I", "I", "O", "O", "K", "N", "N", "N", "N", "C", "C", "R", "C", "C"],
    ["C", "R", "R", "K", "I", "B", "B", "B", "M", "O", "N", "N", "N", "N", "C", "R", "R", "R"],
    ["C", "R", "R", "K", "M", "A", "E", "E", "B", "M", "K", "N", "N", "N", "C", "C", "R", "J"],
    ["C", "C", "R", "K", "M", "A", "A", "A", "B", "M", "O", "K", "N", "N", "N", "C", "J", "J"],
    ["C", "R", "R", "K", "A", "A", "A", "B", "B", "B", "M", "K", "N", "N", "N", "C", "L", "L"],
    ["J", "R", "N", "G", "G", "G", "B", "M", "H", "H", "H", "O", "N", "N", "N", "N", "P", "D"],
    ["J", "J", "N", "G", "H", "H", "B", "M", "M", "H", "G", "G", "N", "N", "N", "N", "P", "D"],
    ["L", "P", "N", "G", "A", "A", "A", "B", "A", "A", "A", "G", "N", "N", "N", "N", "P", "D"],
    ["D", "P", "N", "G", "A", "E", "A", "B", "A", "E", "M", "K", "N", "N", "N", "N", "P", "P"],
    ["D", "P", "N", "N", "M", "B", "G", "H", "A", "E", "M", "K", "N", "N", "N", "N", "N", "P"],
    ["P", "P", "N", "N", "M", "B", "G", "F", "G", "G", "M", "K", "N", "N", "N", "N", "N", "P"],
    ["P", "P", "N", "N", "K", "B", "F", "F", "F", "G", "M", "N", "N", "N", "N", "N", "N", "P"],
    ["P", "P", "N", "N", "N", "K", "B", "B", "G", "G", "O", "K", "N", "N", "N", "N", "N", "P"],
    ["P", "P", "N", "N", "N", "N", "K", "O", "H", "H", "H", "N", "N", "N", "N", "N", "N", "P"],
    ["P", "P", "N", "N", "N", "N", "N", "H", "H", "H", "O", "K", "N", "N", "N", "N", "N", "P"],
    ["P", "P", "N", "N", "N", "N", "N", "O", "G", "G", "G", "G", "K", "N", "N", "N", "N", "P"],
    ["P", "P", "P", "N", "N", "N", "N", "G", "M", "B", "B", "M", "G", "N", "N", "N", "N", "N"],
  ],
  regionColors: {
    A: saharaSand,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: macNCheese,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: lightWisteria,
    L: lightGreen,
    M: atomicTangerine,
    N: coldPurple,
    O: periwinkle,
    P: emerald,
    Q: white,
    R: turquoiseBlue,
  },
  solutionsCount: 1,
  createdBy: "Dan Relaxxe",
  creatorLink: "",
};

export default level;