import {
  altoMain,
  anakiwa,
  bittersweet,
  coldPurple,
  emerald,
  lightGreen,
  nomad,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/373",
  size: 18,
  colorRegions: [
    ["A", "A", "A", "J", "J", "J", "J", "F", "P", "P", "P", "P", "O", "O", "M", "M", "M", "M"],
    ["A", "A", "A", "J", "F", "F", "J", "F", "P", "F", "P", "P", "O", "M", "P", "P", "P", "M"],
    ["A", "L", "L", "F", "L", "L", "F", "F", "F", "F", "F", "P", "P", "P", "P", "M", "M", "M"],
    ["L", "L", "L", "F", "L", "F", "L", "L", "F", "Q", "Q", "F", "P", "P", "M", "P", "P", "M"],
    ["L", "L", "L", "L", "L", "F", "L", "L", "F", "F", "Q", "P", "P", "M", "P", "P", "P", "M"],
    ["L", "L", "L", "L", "L", "L", "L", "L", "F", "F", "Q", "P", "P", "P", "P", "P", "P", "K"],
    ["L", "R", "L", "L", "R", "R", "L", "L", "F", "P", "F", "P", "K", "K", "K", "P", "K", "B"],
    ["L", "L", "R", "R", "L", "R", "L", "L", "F", "P", "P", "P", "P", "P", "K", "K", "C", "B"],
    ["L", "R", "R", "R", "L", "L", "L", "H", "F", "H", "P", "H", "K", "K", "H", "K", "B", "B"],
    ["R", "D", "R", "N", "R", "L", "L", "H", "H", "H", "H", "H", "K", "I", "H", "B", "K", "B"],
    ["D", "D", "R", "N", "N", "R", "L", "H", "H", "H", "H", "H", "I", "I", "H", "B", "B", "B"],
    ["D", "H", "R", "H", "N", "R", "L", "H", "G", "H", "E", "H", "I", "H", "H", "H", "B", "B"],
    ["H", "H", "H", "H", "N", "L", "L", "H", "H", "H", "H", "H", "I", "H", "G", "H", "B", "B"],
    ["E", "H", "G", "H", "N", "N", "L", "H", "E", "H", "G", "H", "H", "H", "H", "H", "H", "H"],
    ["H", "H", "H", "H", "N", "N", "N", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
    ["G", "H", "E", "H", "N", "N", "N", "H", "G", "H", "G", "H", "H", "G", "G", "H", "G", "G"],
    ["H", "H", "H", "H", "H", "E", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H"],
    ["G", "H", "G", "H", "H", "H", "H", "H", "H", "H", "H", "H", "H", "G", "G", "H", "E", "E"],
  ],
  regionColors: {
    A: coldPurple,
    B: coldPurple,
    C: anakiwa,
    D: emerald,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: coldPurple,
    J: coldPurple,
    K: turquoiseBlue,
    L: coldPurple,
    M: lightGreen,
    N: emerald,
    O: coldPurple,
    P: coldPurple,
    Q: coldPurple,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Dan Relaxxe",
  creatorLink: "",
};

export default level;