import {
  altoMain,
  anakiwa,
  atomicTangerine,
  bittersweet,
  celadon,
  chardonnay,
  coldPurple,
  emerald,
  halfBaked,
  lightGreen,
  lightOrchid,
  lightWisteria,
  macNCheese,
  nomad,
  periwinkle,
  saharaSand,
  turquoiseBlue,
  white,
} from "../colors";

const level = {
  path: "/community-level/367",
  size: 18,
  colorRegions: [
    ["M", "P", "P", "P", "M", "J", "P", "P", "P", "P", "P", "K", "P", "P", "P", "P", "P", "P"],
    ["M", "P", "K", "P", "M", "J", "K", "P", "P", "J", "O", "K", "P", "P", "P", "O", "P", "P"],
    ["M", "J", "K", "O", "M", "J", "K", "P", "P", "J", "O", "K", "J", "P", "P", "O", "M", "J"],
    ["I", "J", "K", "O", "I", "I", "K", "O", "M", "J", "O", "I", "J", "O", "P", "O", "M", "J"],
    ["I", "I", "I", "I", "A", "A", "I", "O", "M", "I", "A", "I", "J", "O", "K", "I", "M", "J"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "I", "I", "A", "I", "J", "O", "I", "A", "I", "J"],
    ["E", "E", "A", "A", "R", "R", "R", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "J"],
    ["A", "A", "A", "A", "R", "R", "E", "E", "E", "A", "A", "A", "A", "A", "A", "A", "A", "A"],
    ["E", "E", "E", "A", "R", "R", "R", "A", "A", "A", "A", "E", "E", "E", "E", "A", "N", "N"],
    ["A", "A", "A", "A", "E", "E", "E", "A", "E", "E", "A", "A", "A", "A", "A", "N", "N", "N"],
    ["A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "A", "D", "N", "N", "N", "N", "N"],
    ["F", "F", "F", "F", "F", "F", "F", "A", "A", "A", "A", "D", "D", "D", "N", "N", "N", "N"],
    ["L", "L", "L", "L", "L", "D", "H", "Q", "Q", "Q", "Q", "Q", "D", "D", "D", "D", "N", "N"],
    ["B", "B", "B", "D", "D", "D", "H", "H", "H", "H", "H", "Q", "Q", "D", "D", "D", "D", "D"],
    ["G", "D", "D", "D", "D", "D", "Q", "Q", "C", "C", "H", "C", "Q", "D", "D", "D", "D", "D"],
    ["D", "D", "D", "D", "D", "C", "C", "C", "C", "Q", "H", "C", "C", "C", "C", "C", "C", "D"],
    ["D", "D", "D", "D", "D", "C", "D", "D", "D", "Q", "H", "H", "H", "D", "D", "D", "C", "C"],
    ["D", "D", "D", "D", "D", "C", "D", "D", "D", "D", "D", "D", "H", "D", "D", "D", "D", "D"],
  ],
  regionColors: {
    A: lightWisteria,
    B: chardonnay,
    C: anakiwa,
    D: celadon,
    E: altoMain,
    F: bittersweet,
    G: saharaSand,
    H: nomad,
    I: lightOrchid,
    J: halfBaked,
    K: turquoiseBlue,
    L: atomicTangerine,
    M: lightGreen,
    N: emerald,
    O: periwinkle,
    P: coldPurple,
    Q: macNCheese,
    R: white,
  },
  solutionsCount: 1,
  createdBy: "Dan Relaxxe",
  creatorLink: "",
};

export default level;